sg-22648-shotgrid replace shotgun instances
shotgunsoftware/tk-multi-snapshot pull request #30
Opened 2021-06-08 15:00 UTC by zamu5

2021-06-08 19:19 UTC, jfboismenu requested changes
See my comment.

2021-06-08 19:19 UTC, jfboismenu commented on python/tk_multi_snapshot/snapshot.py
> +                "ShotGrid Save As..."
Please also look for `Shotgun Save As...` in case the client hasn't updated the workfiles app.

2021-06-09 18:31 UTC, jfboismenu approved these changes

2021-06-09 19:32 UTC, mathurf approved these changes
LGTM

Nothing really to test since only README file gets updated

2021-06-09 19:32 UTC, merged